version: '3.8'
services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: admin@123
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    expose:
      - 5432
  api:
    container_name: go-app-backend
    image: <repo url>/<repo name>:latest
    depends_on:
      - postgres
    expose:
      - 8080
    environment:
      - DB_HOST=postgres
      - DB_USER=super_admin
      - DB_PASSWORD=admin@123
      - DB_NAME=postgres
      - DB_PORT=5432
      - ALLOWED_ORIGINS=proxy
    links:
      - "postgres"
  react:
    container_name: frontent_api
    image: <repo url>/<repo name ui>:latest
    depends_on:
      - api
    expose:
      - 3000
    links:
      - "api"
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on: 
      - api      
volumes:
  postgres-db:
    driver: local
